### PR TITLE
Fix date compare problem with Svelte connect. 

### PR DESCRIPTION
**Pull request by Kiho**
Svelte connect does not detect date object changes.

### CODE REVIEW

**Comment by matheusml** [comment]
Thanks for that @Kiho 

Could you please:
- Update the npm version to 4.3.2
- Add this changes to the CHANGELOG file

**Comment by malbernaz** [comment]
It whould good to test if react and preact bindings are working as well. Have you tested it @Kiho?

**Comment by Kiho** [comment]
@malbernaz I did simple check on React example but I did not find same type of issue there.

**Comment by matheusml** [comment]
Thanks @Kiho 

:100:

**Pull request merged**
