### PR TITLE
Disable generation of source maps

### PR DESCRIPTION
**Pull request by eyamenko**
Resulted js file contains a reference to a source maps file. When a bundler appends the content of the file, it also includes a reference to source maps, but a browser then complains that source maps can't be found. Therefore, don't generate source maps for `dist` files.

### CODE REVIEW

**Comment by matheusml** [comment]
Could you please fix the build?

**Comment by eyamenko-infotrack** [comment]
Hi @matheusml . Thanks for noticing. That's done.

**Comment by matheusml** [comment]
@malbernaz and @Kiho 

What do you think about removing **sourcemaps** from the `dist` folder?

**Comment by Kiho** [comment]
I don't think there is anything special, anyway redux-zero code is small enough to debug without source map.

**Comment by matheusml** [comment]
@eyamenko could you please:

- Bump the npm version to 4.9.1
- Add this change to the CHANGELOG file

💯

**Comment by eyamenko** [comment]
@matheusml too easy ;)

**Comment by matheusml** [comment]
Thanks for that @eyamenko 

But now we have some conflicts (because of other PR that was just merged) :(

Could you please fix that?

Thanks a lot for this

**Comment by eyamenko** [comment]
No worries @matheusml

**Comment by matheusml** [comment]
Thanks @eyamenko 

💯

**Pull request merged**
