### PR TITLE
Handle async actions in devtools middleware

### PR DESCRIPTION
**Pull request by Kiho**
https://github.com/concretesolutions/redux-zero/issues/96

### CODE REVIEW

**Comment by matheusml** [comment]
@PedroEsperanca what you think about this?

**Comment by PedroEsperanca** [comment]
The code looks good, but still haven't had a chance to test it

**Comment by PedroEsperanca** [comment]
just tested!

However, I still think it could improve.

I'm now trying to get a hang of redux-zero's dev env and will have a go myself.

What is still not ideal:

- it registers the action only once on the dev tools, even if the state is set multiple times between async requests

- if actions are called within actions the state changes on the further ones seem not to reflect on the dev tools

**Comment by matheusml** [comment]
Hmm, nice thoughts @PedroEsperanca 

What you think about that @Kiho?

**Comment by Kiho** [comment]
Hi @PedroEsperanca
1. I am not sure what that mean, I just notice one thing with your sample, you have one async action and if you call multiple times still state does not change after first call so devtools does not show state change.
2. I don't know I can resolve that issue but if you provide your sample code in the repo then I will try to find out....

**Comment by PedroEsperanca** [comment]
Hey @Kiho !

I'll fully answer you fully on Monday.

Until then, [here's some pseudo code](https://github.com/concretesolutions/redux-zero/issues/100) of how I am calling actions within actions.

**Comment by PedroEsperanca** [comment]
Hey, @Kiho hope this helps:
https://github.com/PedroEsperanca/redux-zero-async-example/blob/master/actions.js

I commented what I think should result in a redux dev-tools entry, but basically, it's every time state is set.

And also not 100% on whether this is the best way to call an action inside an action.
```
mapActions({setState, getState}).asyncAction2(getState());
```

**Comment by Kiho** [comment]
Hi @PedroEsperanca, I made things work as you described here 

https://github.com/Kiho/redux-zero/blob/devtools-async2/examples/preact/counter/actions.js
https://github.com/Kiho/redux-zero/blob/devtools-async2/examples/preact/counter/store.js

@matheusml  Let me know if you want to include code in store.js to core, I am not sure this is good practice or not, otherwise you can merge this PR as is for bug fix at current state.

**Comment by PedroEsperanca** [comment]
Ah, I see, so it's not easy to log an action in the dev tools when calling setState.

Well, that's not so important.

What would be really nice is to **be able to call an action from within an action**, which is, in fact, more in sync with best practices and would also solve the requirement anyway.

With your suggestions @Kiho **asyncAction2** is getting logged on the dev tools as **asyncAction1**, and everything else as **dispatch**.
This is what logs after calling **asyncAction1** which then calls **asyncAction2**:
image

**Comment by PedroEsperanca** [comment]
```
return mapActions({setState, getState}).asyncAction2(getState());
```

This is how we're calling **asyncAction2**, which is clearly not the best looking code also :p

**Comment by PedroEsperanca** [comment]
Another thing I noticed is that we can't put a **.then()** after calling an action in a component.
This would also help with such flows where actions depend on other actions (even thouh I would prefer to keep the flow logic within the actions)

**Comment by Kiho** [comment]
Normally I can log single name for action, that's why you  see asycAction1 than asycAction2 but you are seeing the state which is result of asycAction2,
I bind generic action `dispatch` for just traceability. if you want do something more than you can consider to create middleware instead of asyncAction like this https://github.com/Kiho/redux-zero/blob/middleware-svt/examples/svelte/middleware/src/middleware/promise-middleware.ts

**Comment by PedroEsperanca** [comment]
That solution is interesting but a bit limiting.

So calling an action inside actions that actually log a new action, is it possible?
It would solve everything.

Also, it's needed for integrating with analytics.

**Comment by PedroEsperanca** [comment]
I've found what looks to me like a better solution for calling actions inside actions [here](https://github.com/PedroEsperanca/redux-zero-async-example/blob/master/actions.js)

What I do is bind the actions I want to call inside other actions like so:
```
const { asyncAction2 } = bindActions(mapActions, store);
```

Then I can just call them like:
```
asyncAction2('test param');
```

Does this look like a good solution?

**Comment by PedroEsperanca** [comment]
@matheusml with this way of calling actions inside actions works perfectly with the changes in this PR.

I'd say it's good to merge.

**Comment by matheusml** [comment]
@Kiho 
Please add this change to the CHANGELOG file and bump the version to `4.10.1`.

@esperancaJS 
About your quote:

> What would be really nice is to be able to call an action from within an action, which is, in fact, more in sync with best practices and would also solve the requirement anyway.

I don't think that should be the case. An action should not call another action. If you want to reuse code, what you can do is create a function (that's not an action), for example.

**Comment by esperancaJS** [comment]
@matheusml why not?

By calling another action you map out the flow which makes it easy to debug.
By calling just a function there is no tracking or any of the advantages of the redux dev-tools or middlewares.

In redux you have redux-thunk or redux-sagas and in ngrx/store you have ngrx/effects for async actions, where multiple actions are also dispatched, making this a commonly used pattern already.

**Comment by matheusml** [comment]
@esperancaJS this is kind of out of scope of this PR. But if you still feel like actions should be call from another actions, please feel free to open an issue with this.

Thanks

**Pull request merged**
