### PR TITLE
adding HOC connect for preact

### PR DESCRIPTION
**Pull request by PedroEsperanca**
nearly added `connect` for preact

just one last issue to sort:
image

### CODE REVIEW

**Comment by matheusml** [comment]
There's a closed PR with the same unsolved error. We'll have to research deeper :(

**Comment by PedroEsperanca** [comment]
fixed! 🎉

**Comment by matheusml** [comment]
This is awesome @PedroEsperanca 

But could you please:
- Add this change to the CHANGELOG
- Bump the npm version to 4.10.0

**Comment by PedroEsperanca** [comment]
👌

**Pull request merged**
